### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mcclanahan**
Removed expired RangeForce classes and and added Pluralsight link

### CODE REVIEW

**Comment by gerryguy311** [comment]
The RangeForce class didnt seem expired. Did you register for it and it
said expired?  Thanks for contributing and for the Pluralsight MSFT entry.

**Comment by gerryguy311** [comment]
Im committing but will add back rangeforce based on your response.

**Comment by mcclanahan** [comment]
Last night the links did not bring up a registration page and today it works so please add the Rangeforce links back.

**Comment by gerryguy311** [comment]
ok. cool. Thanks for taking the time to be part of this.

**Pull request merged**
